# Generated by Django 4.2.6 on 2024-05-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_msgupdate_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadofuerza',
            name='nomPuntoRevision',
            field=models.CharField(max_length=350),
        ),
    ]
