# Generated by Django 4.2.6 on 2024-11-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_estadofuerza_nompuntorevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisuadidosPunto',
            fields=[
                ('idDisuadidos', models.AutoField(primary_key=True, serialize=False)),
                ('oficinaRepre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('nombreAgente', models.CharField(blank=True, max_length=300)),
                ('tipoPuntoRevision', models.CharField(blank=True, max_length=300)),
                ('nombrePuntoRevision', models.CharField(blank=True, max_length=300)),
                ('numDisiadidos', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
