# Generated by Django 4.2.6 on 2024-07-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_estadofuerza_nompuntorevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
