# Generated by Django 4.2.6 on 2024-07-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_alter_usuario_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescatepunto',
            name='numPresuntosDelincuentes',
            field=models.IntegerField(default=0),
        ),
    ]
