# Generated by Django 4.2.6 on 2024-11-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_disuadidospunto_alter_usuario_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgupdate',
            name='info',
            field=models.BooleanField(default=False),
        ),
    ]
